api_token_login:
    path: /api/token/login
gesdinet_jwt_refresh_token:
    path: /api/token/refresh
controllers:
    resource: ../../src/Controller/
    type: annotation
when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
